#!/usr/bin/env bash
#
# PreToolUse hook: makes "do not edit these" structural instead of advisory.
#
# A PreToolUse deny fires before any permission-mode check, so it holds even
# under bypassPermissions / --dangerously-skip-permissions.
#
#   themes/    git submodule — CLAUDE.md says do not edit
#   public/    build output, regenerated by every build
#   resources/ Hugo's asset cache
#   ~/.claude/ outside source control (see .claude/memory/, prefer-source-control)
set -uo pipefail

input=$(cat)
file=$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')
[ -z "$file" ] && exit 0

deny() {
  jq -nc --arg r "$1" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: $r
    }
  }'
  exit 0
}

case "$file" in
  "$HOME"/.claude/*)
    deny "$file is outside source control. Put project config in the repo's .claude/ instead, so the change is reviewable and revertible."
    ;;
esac

root="${CLAUDE_PROJECT_DIR:-$PWD}"
case "$file" in
  "$root"/*) rel="${file#"$root"/}" ;;
  /*)        exit 0 ;;   # elsewhere on disk (e.g. scratchpad) — not our business
  *)         rel="$file" ;;
esac

case "$rel" in
  themes/*)
    deny "themes/hugo-book is a git submodule and must not be edited. To change how pages render, add an override under layouts/ instead — it shadows the theme's template of the same name."
    ;;
  public/*|resources/*)
    deny "$rel is build output and is overwritten on every build. Edit the source under content/, layouts/, or static/."
    ;;
esac

exit 0
